package org.globalplatform.mobilesubscriptionlifecyclenotification;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-06T15:50:05.626+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "MobileSubscriptionLifeCycleNotificationService", 
                  wsdlLocation = "MobileSubscriptionLifeCycleNotification.wsdl",
                  targetNamespace = "http://globalplatform.org/mobilesubscriptionlifecyclenotification") 
public class MobileSubscriptionLifeCycleNotificationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://globalplatform.org/mobilesubscriptionlifecyclenotification", "MobileSubscriptionLifeCycleNotificationService");
    public final static QName MobileSubscriptionLifeCycleNotificationEndPoint = new QName("http://globalplatform.org/mobilesubscriptionlifecyclenotification", "MobileSubscriptionLifeCycleNotificationEndPoint");
    static {
        URL url = MobileSubscriptionLifeCycleNotificationService.class.getResource("MobileSubscriptionLifeCycleNotification.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(MobileSubscriptionLifeCycleNotificationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "MobileSubscriptionLifeCycleNotification.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public MobileSubscriptionLifeCycleNotificationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MobileSubscriptionLifeCycleNotificationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MobileSubscriptionLifeCycleNotificationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns MobileSubscriptionLifeCycleNotification
     */
    @WebEndpoint(name = "MobileSubscriptionLifeCycleNotificationEndPoint")
    public MobileSubscriptionLifeCycleNotification getMobileSubscriptionLifeCycleNotificationEndPoint() {
        return super.getPort(MobileSubscriptionLifeCycleNotificationEndPoint, MobileSubscriptionLifeCycleNotification.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MobileSubscriptionLifeCycleNotification
     */
    @WebEndpoint(name = "MobileSubscriptionLifeCycleNotificationEndPoint")
    public MobileSubscriptionLifeCycleNotification getMobileSubscriptionLifeCycleNotificationEndPoint(WebServiceFeature... features) {
        return super.getPort(MobileSubscriptionLifeCycleNotificationEndPoint, MobileSubscriptionLifeCycleNotification.class, features);
    }

}
