package org.globalplatform.delegatedmanagement;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-06T15:47:43.040+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "DelegatedManagementService", 
                  wsdlLocation = "DelegatedManagement.wsdl",
                  targetNamespace = "http://globalplatform.org/delegatedmanagement") 
public class DelegatedManagementService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://globalplatform.org/delegatedmanagement", "DelegatedManagementService");
    public final static QName DelegatedManagementEndpoint = new QName("http://globalplatform.org/delegatedmanagement", "DelegatedManagementEndpoint");
    static {
        URL url = DelegatedManagementService.class.getResource("DelegatedManagement.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(DelegatedManagementService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "DelegatedManagement.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public DelegatedManagementService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DelegatedManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DelegatedManagementService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns DelegatedManagement
     */
    @WebEndpoint(name = "DelegatedManagementEndpoint")
    public DelegatedManagement getDelegatedManagementEndpoint() {
        return super.getPort(DelegatedManagementEndpoint, DelegatedManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DelegatedManagement
     */
    @WebEndpoint(name = "DelegatedManagementEndpoint")
    public DelegatedManagement getDelegatedManagementEndpoint(WebServiceFeature... features) {
        return super.getPort(DelegatedManagementEndpoint, DelegatedManagement.class, features);
    }

}
