package org.globalplatform.delegatedmanagement;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-06T15:47:42.995+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://globalplatform.org/delegatedmanagement", name = "DelegatedManagement")
@XmlSeeAlso({org.globalplatform.namespaces.systems_profiles._1_1.ObjectFactory.class, generated.ObjectFactory.class, org.globalplatform.namespaces.systems_messaging._2_0.ObjectFactory.class, org.w3._2000._09.xmldsig.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DelegatedManagement {

    @WebResult(name = "VerifyDMReceiptResponse", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.0.1", partName = "VerifyDMReceiptResponse")
    @WebMethod(operationName = "VerifyDMReceipt", action = "VerifyDMReceipt")
    public org.globalplatform.namespaces.systems_messaging._2_0.VerifyDMReceiptResponseType verifyDMReceipt(
        @WebParam(partName = "VerifyDMReceiptRequest", name = "VerifyDMReceiptRequest", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.0.1")
        org.globalplatform.namespaces.systems_messaging._2_0.VerifyDMReceiptRequestType verifyDMReceiptRequest
    );

    @WebResult(name = "GenerateDMTokenResponse", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.0.1", partName = "GenerateDMTokenResponse")
    @WebMethod(operationName = "GenerateDMToken", action = "GenerateDMToken")
    public org.globalplatform.namespaces.systems_messaging._2_0.GenerateDMTokenResponseType generateDMToken(
        @WebParam(partName = "GenerateDMTokenRequest", name = "GenerateDMTokenRequest", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.0.1")
        org.globalplatform.namespaces.systems_messaging._2_0.GenerateDMTokenRequestType generateDMTokenRequest
    );
}
