package org.globalplatform.scriptsending;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-06T15:50:18.301+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://globalplatform.org/scriptsending", name = "ScriptSending")
@XmlSeeAlso({org.globalplatform.namespaces.systems_profiles._1_1.ObjectFactory.class, generated.ObjectFactory.class, org.globalplatform.namespaces.systems_messaging._2_0.ObjectFactory.class, org.w3._2000._09.xmldsig.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ScriptSending {

    @WebResult(name = "EndConversationResponse", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.0.1", partName = "EndConversationResponse")
    @WebMethod(operationName = "EndConversation", action = "EndConversation")
    public org.globalplatform.namespaces.systems_messaging._2_0.EndConversationResponseType endConversation(
        @WebParam(partName = "EndConversationRequest", name = "EndConversationRequest", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.0.1")
        org.globalplatform.namespaces.systems_messaging._2_0.EndConversationRequestType endConversationRequest
    );

    @Oneway
    @WebMethod(operationName = "BeginConversation", action = "BeginConversation")
    public void beginConversation(
        @WebParam(partName = "BeginConversationRequest", name = "BeginConversationRequest", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.0.1")
        org.globalplatform.namespaces.systems_messaging._2_0.BeginConversationRequestType beginConversationRequest
    );

    @Oneway
    @WebMethod(operationName = "SendScript", action = "SendScript")
    public void sendScript(
        @WebParam(partName = "SendScriptRequest", name = "SendScriptRequest", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.0.1")
        org.globalplatform.namespaces.systems_messaging._2_0.SendScriptRequestType sendScriptRequest
    );
}
