package org.globalplatform.sp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-06T15:49:40.936+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "SPService", 
                  wsdlLocation = "DIAD_SP.wsdl",
                  targetNamespace = "http://globalplatform.org/sp") 
public class SPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://globalplatform.org/sp", "SPService");
    public final static QName SPEndPoint = new QName("http://globalplatform.org/sp", "SPEndPoint");
    static {
        URL url = SPService.class.getResource("DIAD_SP.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SPService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "DIAD_SP.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public SPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SPService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SP
     */
    @WebEndpoint(name = "SPEndPoint")
    public SP getSPEndPoint() {
        return super.getPort(SPEndPoint, SP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SP
     */
    @WebEndpoint(name = "SPEndPoint")
    public SP getSPEndPoint(WebServiceFeature... features) {
        return super.getPort(SPEndPoint, SP.class, features);
    }

}
