package org.globalplatform.deviceapplicationbinding;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-06T15:48:15.310+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "DeviceApplicationBindingCallBackService", 
                  wsdlLocation = "DeviceApplicationBindingCallBack.wsdl",
                  targetNamespace = "http://globalplatform.org/deviceapplicationbinding") 
public class DeviceApplicationBindingCallBackService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://globalplatform.org/deviceapplicationbinding", "DeviceApplicationBindingCallBackService");
    public final static QName DeviceApplicationBindingCallBackEndpoint = new QName("http://globalplatform.org/deviceapplicationbinding", "DeviceApplicationBindingCallBackEndpoint");
    static {
        URL url = DeviceApplicationBindingCallBackService.class.getResource("DeviceApplicationBindingCallBack.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(DeviceApplicationBindingCallBackService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "DeviceApplicationBindingCallBack.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public DeviceApplicationBindingCallBackService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DeviceApplicationBindingCallBackService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeviceApplicationBindingCallBackService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns DeviceApplicationBindingCallBack
     */
    @WebEndpoint(name = "DeviceApplicationBindingCallBackEndpoint")
    public DeviceApplicationBindingCallBack getDeviceApplicationBindingCallBackEndpoint() {
        return super.getPort(DeviceApplicationBindingCallBackEndpoint, DeviceApplicationBindingCallBack.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeviceApplicationBindingCallBack
     */
    @WebEndpoint(name = "DeviceApplicationBindingCallBackEndpoint")
    public DeviceApplicationBindingCallBack getDeviceApplicationBindingCallBackEndpoint(WebServiceFeature... features) {
        return super.getPort(DeviceApplicationBindingCallBackEndpoint, DeviceApplicationBindingCallBack.class, features);
    }

}
