package org.globalplatform.deviceapplicationbinding;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-06T15:47:55.445+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "DeviceApplicationBindingService", 
                  wsdlLocation = "DeviceApplicationBinding.wsdl",
                  targetNamespace = "http://globalplatform.org/deviceapplicationbinding") 
public class DeviceApplicationBindingService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://globalplatform.org/deviceapplicationbinding", "DeviceApplicationBindingService");
    public final static QName DeviceApplicationBindingEndpoint = new QName("http://globalplatform.org/deviceapplicationbinding", "DeviceApplicationBindingEndpoint");
    static {
        URL url = DeviceApplicationBindingService.class.getResource("DeviceApplicationBinding.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(DeviceApplicationBindingService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "DeviceApplicationBinding.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public DeviceApplicationBindingService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DeviceApplicationBindingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeviceApplicationBindingService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns DeviceApplicationBinding
     */
    @WebEndpoint(name = "DeviceApplicationBindingEndpoint")
    public DeviceApplicationBinding getDeviceApplicationBindingEndpoint() {
        return super.getPort(DeviceApplicationBindingEndpoint, DeviceApplicationBinding.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeviceApplicationBinding
     */
    @WebEndpoint(name = "DeviceApplicationBindingEndpoint")
    public DeviceApplicationBinding getDeviceApplicationBindingEndpoint(WebServiceFeature... features) {
        return super.getPort(DeviceApplicationBindingEndpoint, DeviceApplicationBinding.class, features);
    }

}
