package org.globalplatform.deviceapplicationmanagement;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-06T15:48:38.330+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "DeviceApplicationManagementCallBackService", 
                  wsdlLocation = "DeviceApplicationManagementCallBack.wsdl",
                  targetNamespace = "http://globalplatform.org/deviceapplicationmanagement") 
public class DeviceApplicationManagementCallBackService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://globalplatform.org/deviceapplicationmanagement", "DeviceApplicationManagementCallBackService");
    public final static QName DeviceApplicationManagementCallBackEndPoint = new QName("http://globalplatform.org/deviceapplicationmanagement", "DeviceApplicationManagementCallBackEndPoint");
    static {
        URL url = DeviceApplicationManagementCallBackService.class.getResource("DeviceApplicationManagementCallBack.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(DeviceApplicationManagementCallBackService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "DeviceApplicationManagementCallBack.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public DeviceApplicationManagementCallBackService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DeviceApplicationManagementCallBackService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeviceApplicationManagementCallBackService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns DeviceApplicationManagementCallBack
     */
    @WebEndpoint(name = "DeviceApplicationManagementCallBackEndPoint")
    public DeviceApplicationManagementCallBack getDeviceApplicationManagementCallBackEndPoint() {
        return super.getPort(DeviceApplicationManagementCallBackEndPoint, DeviceApplicationManagementCallBack.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeviceApplicationManagementCallBack
     */
    @WebEndpoint(name = "DeviceApplicationManagementCallBackEndPoint")
    public DeviceApplicationManagementCallBack getDeviceApplicationManagementCallBackEndPoint(WebServiceFeature... features) {
        return super.getPort(DeviceApplicationManagementCallBackEndPoint, DeviceApplicationManagementCallBack.class, features);
    }

}
