package org.globalplatform.deviceapplicationmanagement;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-06T15:48:38.275+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://globalplatform.org/deviceapplicationmanagement", name = "DeviceApplicationManagementCallBack")
@XmlSeeAlso({org.globalplatform.namespaces.systems_profiles._1_1.ObjectFactory.class, generated.ObjectFactory.class, org.globalplatform.namespaces.systems_messaging._2_0.ObjectFactory.class, org.w3._2000._09.xmldsig.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DeviceApplicationManagementCallBack {

    @Oneway
    @WebMethod(operationName = "DeleteDeviceApplication", action = "DeleteDeviceApplication")
    public void deleteDeviceApplication(
        @WebParam(partName = "DeleteDeviceApplicationResponse", name = "DeleteDeviceApplicationResponse", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.0.1")
        org.globalplatform.namespaces.systems_messaging._2_0.DeleteDeviceApplicationResponseType deleteDeviceApplicationResponse
    );

    @Oneway
    @WebMethod(operationName = "LoadDeviceApplication", action = "LoadDeviceApplication")
    public void loadDeviceApplication(
        @WebParam(partName = "LoadDeviceApplicationResponse", name = "LoadDeviceApplicationResponse", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.0.1")
        org.globalplatform.namespaces.systems_messaging._2_0.LoadDeviceApplicationResponseType loadDeviceApplicationResponse
    );
}
