package org.globalplatform.ccmcertificatesmanagement;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-06T15:47:22.535+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "CCCMCertificatesManagementService", 
                  wsdlLocation = "CCCMCertificatesManagement.wsdl",
                  targetNamespace = "http://globalplatform.org/ccmcertificatesmanagement") 
public class CCCMCertificatesManagementService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://globalplatform.org/ccmcertificatesmanagement", "CCCMCertificatesManagementService");
    public final static QName CCCMCertificatesManagementEndpoint = new QName("http://globalplatform.org/ccmcertificatesmanagement", "CCCMCertificatesManagementEndpoint");
    static {
        URL url = CCCMCertificatesManagementService.class.getResource("CCCMCertificatesManagement.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(CCCMCertificatesManagementService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "CCCMCertificatesManagement.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public CCCMCertificatesManagementService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CCCMCertificatesManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CCCMCertificatesManagementService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CCCMCertificatesManagement
     */
    @WebEndpoint(name = "CCCMCertificatesManagementEndpoint")
    public CCCMCertificatesManagement getCCCMCertificatesManagementEndpoint() {
        return super.getPort(CCCMCertificatesManagementEndpoint, CCCMCertificatesManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCCMCertificatesManagement
     */
    @WebEndpoint(name = "CCCMCertificatesManagementEndpoint")
    public CCCMCertificatesManagement getCCCMCertificatesManagementEndpoint(WebServiceFeature... features) {
        return super.getPort(CCCMCertificatesManagementEndpoint, CCCMCertificatesManagement.class, features);
    }

}
