package org.globalplatform.ccmcertificatesmanagement;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-06T15:47:22.490+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://globalplatform.org/ccmcertificatesmanagement", name = "CCCMCertificatesManagement")
@XmlSeeAlso({org.globalplatform.namespaces.systems_profiles._1_1.ObjectFactory.class, generated.ObjectFactory.class, org.globalplatform.namespaces.systems_messaging._2_0.ObjectFactory.class, org.w3._2000._09.xmldsig.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CCCMCertificatesManagement {

    @WebResult(name = "EnrollSSDOwnerCertificateResponse", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.0.1", partName = "EnrollSSDOwnerCertificateResponse")
    @WebMethod(operationName = "EnrollSSDOwnerCertificate", action = "EnrollSSDOwnerCertificate")
    public org.globalplatform.namespaces.systems_messaging._2_0.EnrollSSDOwnerCertificateResponseType enrollSSDOwnerCertificate(
        @WebParam(partName = "EnrollSSDOwnerCertificateRequest", name = "EnrollSSDOwnerCertificateRequest", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.0.1")
        org.globalplatform.namespaces.systems_messaging._2_0.EnrollSSDOwnerCertificateRequestType enrollSSDOwnerCertificateRequest
    );
}
