package org.globalplatform.requestapplication;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-06T15:49:27.961+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "RequestApplicationService", 
                  wsdlLocation = "DIAD_RequestApplication.wsdl",
                  targetNamespace = "http://globalplatform.org/requestapplication") 
public class RequestApplicationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://globalplatform.org/requestapplication", "RequestApplicationService");
    public final static QName RequestApplicationEndPoint = new QName("http://globalplatform.org/requestapplication", "RequestApplicationEndPoint");
    static {
        URL url = RequestApplicationService.class.getResource("DIAD_RequestApplication.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(RequestApplicationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "DIAD_RequestApplication.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public RequestApplicationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RequestApplicationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RequestApplicationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RequestApplication
     */
    @WebEndpoint(name = "RequestApplicationEndPoint")
    public RequestApplication getRequestApplicationEndPoint() {
        return super.getPort(RequestApplicationEndPoint, RequestApplication.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RequestApplication
     */
    @WebEndpoint(name = "RequestApplicationEndPoint")
    public RequestApplication getRequestApplicationEndPoint(WebServiceFeature... features) {
        return super.getPort(RequestApplicationEndPoint, RequestApplication.class, features);
    }

}
