package org.globalplatform.cardcontentmanagement;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-06T15:46:32.235+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "CardContentManagementService", 
                  wsdlLocation = "CardContentManagement.wsdl",
                  targetNamespace = "http://globalplatform.org/cardcontentmanagement") 
public class CardContentManagementService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://globalplatform.org/cardcontentmanagement", "CardContentManagementService");
    public final static QName CardContentManagementEndpoint = new QName("http://globalplatform.org/cardcontentmanagement", "CardContentManagementEndpoint");
    static {
        URL url = CardContentManagementService.class.getResource("CardContentManagement.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(CardContentManagementService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "CardContentManagement.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public CardContentManagementService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CardContentManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CardContentManagementService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CardContentManagement
     */
    @WebEndpoint(name = "CardContentManagementEndpoint")
    public CardContentManagement getCardContentManagementEndpoint() {
        return super.getPort(CardContentManagementEndpoint, CardContentManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CardContentManagement
     */
    @WebEndpoint(name = "CardContentManagementEndpoint")
    public CardContentManagement getCardContentManagementEndpoint(WebServiceFeature... features) {
        return super.getPort(CardContentManagementEndpoint, CardContentManagement.class, features);
    }

}
