package org.globalplatform.appman;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-05-29T11:51:32.515+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "AppmanService", 
                  wsdlLocation = "DIAD_SignatureTest_Appman.wsdl.test",
                  targetNamespace = "http://globalplatform.org/appman") 
public class AppmanService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://globalplatform.org/appman", "AppmanService");
    public final static QName AppmanEndPoint = new QName("http://globalplatform.org/appman", "AppmanEndPoint");
    static {
        URL url = AppmanService.class.getResource("DIAD_SignatureTest_Appman.wsdl.test");
        if (url == null) {
            java.util.logging.Logger.getLogger(AppmanService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "DIAD_SignatureTest_Appman.wsdl.test");
        }       
        WSDL_LOCATION = url;
    }

    public AppmanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AppmanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AppmanService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns Appman
     */
    @WebEndpoint(name = "AppmanEndPoint")
    public Appman getAppmanEndPoint() {
        return super.getPort(AppmanEndPoint, Appman.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Appman
     */
    @WebEndpoint(name = "AppmanEndPoint")
    public Appman getAppmanEndPoint(WebServiceFeature... features) {
        return super.getPort(AppmanEndPoint, Appman.class, features);
    }

}
