package org.globalplatform.appman;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-05-29T11:51:32.451+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://globalplatform.org/appman", name = "Appman")
@XmlSeeAlso({org.globalplatform.namespaces.systems_profiles._1_1.ObjectFactory.class, org.w3._2000._09.xmldsig.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Appman {

    @WebResult(name = "SignatureTest", targetNamespace = "http://namespaces.globalplatform.org/systems-profiles/1.1.1", partName = "GetAppProfileResponse")
    @WebMethod(operationName = "GetAppProfile", action = "GetAppProfile")
    public org.globalplatform.namespaces.systems_profiles._1_1.SignatureTest getAppProfile(
        @WebParam(partName = "GetAppProfileRequest", name = "SignatureTest", targetNamespace = "http://namespaces.globalplatform.org/systems-profiles/1.1.1")
        org.globalplatform.namespaces.systems_profiles._1_1.SignatureTest getAppProfileRequest
    );
}
