package org.globalplatform.deviceinfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-06T15:48:50.310+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://globalplatform.org/deviceinfo", name = "DeviceInfo")
@XmlSeeAlso({org.globalplatform.namespaces.systems_profiles._1_1.ObjectFactory.class, generated.ObjectFactory.class, org.globalplatform.namespaces.systems_messaging._2_0.ObjectFactory.class, org.w3._2000._09.xmldsig.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DeviceInfo {

    @WebResult(name = "GetDeviceCapabilityProfileIdResponse", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.0.1", partName = "GetDeviceCapabilityProfileIdResponse")
    @WebMethod(operationName = "GetDeviceCapabilityProfileId", action = "GetDeviceCapabilityProfileId")
    public org.globalplatform.namespaces.systems_messaging._2_0.GetDeviceCapabilityProfileIdResponseType getDeviceCapabilityProfileId(
        @WebParam(partName = "GetDeviceCapabilityProfileIdRequest", name = "GetDeviceCapabilityProfileIdRequest", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.0.1")
        org.globalplatform.namespaces.systems_messaging._2_0.GetDeviceCapabilityProfileIdRequestType getDeviceCapabilityProfileIdRequest
    );
}
