package org.globalplatform.seaudit;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-06T15:51:05.766+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "SEAuditService", 
                  wsdlLocation = "SEAudit.wsdl",
                  targetNamespace = "http://globalplatform.org/seaudit") 
public class SEAuditService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://globalplatform.org/seaudit", "SEAuditService");
    public final static QName SEAuditEndPoint = new QName("http://globalplatform.org/seaudit", "SEAuditEndPoint");
    static {
        URL url = SEAuditService.class.getResource("SEAudit.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SEAuditService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "SEAudit.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public SEAuditService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SEAuditService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SEAuditService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SEAudit
     */
    @WebEndpoint(name = "SEAuditEndPoint")
    public SEAudit getSEAuditEndPoint() {
        return super.getPort(SEAuditEndPoint, SEAudit.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SEAudit
     */
    @WebEndpoint(name = "SEAuditEndPoint")
    public SEAudit getSEAuditEndPoint(WebServiceFeature... features) {
        return super.getPort(SEAuditEndPoint, SEAudit.class, features);
    }

}
