package org.globalplatform.scwsmanagement;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-06T15:50:42.486+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://globalplatform.org/scwsmanagement", name = "SCWSManagement")
@XmlSeeAlso({org.globalplatform.namespaces.systems_profiles._1_1.ObjectFactory.class, generated.ObjectFactory.class, org.globalplatform.namespaces.systems_messaging._2_0.ObjectFactory.class, org.w3._2000._09.xmldsig.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SCWSManagement {

    @Oneway
    @WebMethod(operationName = "LoadSCWSServicePortal", action = "LoadSCWSServicePortal")
    public void loadSCWSServicePortal(
        @WebParam(partName = "LoadSCWSServicePortalRequest", name = "LoadSCWSServicePortalRequest", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.0.1")
        org.globalplatform.namespaces.systems_messaging._2_0.LoadSCWSServicePortalRequestType loadSCWSServicePortalRequest
    );

    @Oneway
    @WebMethod(operationName = "DeleteSCWSServicePortal", action = "DeleteSCWSServicePortal")
    public void deleteSCWSServicePortal(
        @WebParam(partName = "DeleteSCWSServicePortalRequest", name = "DeleteSCWSServicePortalRequest", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.0.1")
        org.globalplatform.namespaces.systems_messaging._2_0.DeleteSCWSServicePortalRequestType deleteSCWSServicePortalRequest
    );
}
