package org.globalplatform.scwsmanagement;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-06T15:50:42.536+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "SCWSManagementService", 
                  wsdlLocation = "SCWSManagement.wsdl",
                  targetNamespace = "http://globalplatform.org/scwsmanagement") 
public class SCWSManagementService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://globalplatform.org/scwsmanagement", "SCWSManagementService");
    public final static QName SCWSManagementEndPoint = new QName("http://globalplatform.org/scwsmanagement", "SCWSManagementEndPoint");
    static {
        URL url = SCWSManagementService.class.getResource("SCWSManagement.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SCWSManagementService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "SCWSManagement.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public SCWSManagementService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SCWSManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SCWSManagementService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SCWSManagement
     */
    @WebEndpoint(name = "SCWSManagementEndPoint")
    public SCWSManagement getSCWSManagementEndPoint() {
        return super.getPort(SCWSManagementEndPoint, SCWSManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SCWSManagement
     */
    @WebEndpoint(name = "SCWSManagementEndPoint")
    public SCWSManagement getSCWSManagementEndPoint(WebServiceFeature... features) {
        return super.getPort(SCWSManagementEndPoint, SCWSManagement.class, features);
    }

}
