package org.globalplatform.seinfo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-06T15:51:34.366+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "SEInfoService", 
                  wsdlLocation = "SEInfo.wsdl",
                  targetNamespace = "http://globalplatform.org/seinfo") 
public class SEInfoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://globalplatform.org/seinfo", "SEInfoService");
    public final static QName SEInfoEndPoint = new QName("http://globalplatform.org/seinfo", "SEInfoEndPoint");
    static {
        URL url = SEInfoService.class.getResource("SEInfo.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SEInfoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "SEInfo.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public SEInfoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SEInfoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SEInfoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SEInfo
     */
    @WebEndpoint(name = "SEInfoEndPoint")
    public SEInfo getSEInfoEndPoint() {
        return super.getPort(SEInfoEndPoint, SEInfo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SEInfo
     */
    @WebEndpoint(name = "SEInfoEndPoint")
    public SEInfo getSEInfoEndPoint(WebServiceFeature... features) {
        return super.getPort(SEInfoEndPoint, SEInfo.class, features);
    }

}
