package org.globalplatform.servicelifecyclenotification;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-06T15:52:05.173+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "ServiceLifeCycleNotificationService", 
                  wsdlLocation = "ServiceLifeCycleNotification.wsdl",
                  targetNamespace = "http://globalplatform.org/servicelifecyclenotification") 
public class ServiceLifeCycleNotificationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://globalplatform.org/servicelifecyclenotification", "ServiceLifeCycleNotificationService");
    public final static QName ServiceLifeCycleNotificationEndPoint = new QName("http://globalplatform.org/servicelifecyclenotification", "ServiceLifeCycleNotificationEndPoint");
    static {
        URL url = ServiceLifeCycleNotificationService.class.getResource("ServiceLifeCycleNotification.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ServiceLifeCycleNotificationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "ServiceLifeCycleNotification.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public ServiceLifeCycleNotificationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceLifeCycleNotificationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceLifeCycleNotificationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ServiceLifeCycleNotification
     */
    @WebEndpoint(name = "ServiceLifeCycleNotificationEndPoint")
    public ServiceLifeCycleNotification getServiceLifeCycleNotificationEndPoint() {
        return super.getPort(ServiceLifeCycleNotificationEndPoint, ServiceLifeCycleNotification.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceLifeCycleNotification
     */
    @WebEndpoint(name = "ServiceLifeCycleNotificationEndPoint")
    public ServiceLifeCycleNotification getServiceLifeCycleNotificationEndPoint(WebServiceFeature... features) {
        return super.getPort(ServiceLifeCycleNotificationEndPoint, ServiceLifeCycleNotification.class, features);
    }

}
